name: Helm

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '**/helm.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - '**/helm.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/mondoo-assessment-app

permissions:
  contents: write

jobs:
  helm:
    name: Test and release helm chart
    runs-on: ubuntu-latest
    concurrency: helm-charts
    steps:
      - uses: actions/checkout@v4
        with:  
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
          fi
      
      - name: Set chart version
        run: |
          cd charts
          sed -i 's/version: 0.1.0/version: 0.1.'$GITHUB_RUN_NUMBER'/g' */Chart.yaml
      
      - name: Determine app version
        id: app-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [ "${{ inputs.tag }}" = "" ]; then
            TAG=$(gh release view -R lexicoder/mondo-playground --json tagName -q .tagName)
            VERSION=${TAG#v}
          else
            VERSION=${{ inputs.tag }}
          fi
          echo "APP_VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set app version
        run: |
          cd charts
          sed -i 's/appVersion: "1.16.0"/appVersion: '\"${{ steps.app-version.outputs.APP_VERSION }}\"'/g' */Chart.yaml
          cat mondoo-assessment-app/Chart.yaml

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
          
      - name: Create secret
        run: |
          kubectl create namespace testing
          kubectl create secret -n testing docker-registry ghcr-login-secret --docker-server=https://ghcr.io --docker-username=${{ github.repository_owner }} --docker-password=${{ secrets.GH_PAT }}

      - name: Run chart-testing (install)
        run: |
          ct install --all --namespace testing

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
